Pandas is a Python library used to organize, analyze, and manipulate structured data using Series and DataFrame

In [93]:
import pandas as pd

**Data Structures**

In [94]:
pd.Series([1,2,3,4])  #Series

0    1
1    2
2    3
3    4
dtype: int64

In [95]:
pd.DataFrame({
    "Name":["RC","Rakul"],
    "Gender":["Male","Female"],
    "Age":[39,33]
})

    Name  Gender  Age
0     RC    Male   39
1  Rakul  Female   33

**Data Loading Functions**`

In [96]:
#pd.read_csv("file.csv")
#pd.read_excel("file.xlsx")
#pd.read_sql()

In [97]:
#IPL data instead of dataset

data = {
    "Player": [
        "Virat Kohli",
        "Rohit Sharma",
        "MS Dhoni",
        "KL Rahul",
        "David Warner",
        "AB de Villiers",
        "Hardik Pandya",
        "Jasprit Bumrah",
        "Ravindra Jadeja",
        "Shubman Gill"
    ],

    "Age": [35, 36, 42, 32, 37, 40, 31, 30, 35, 25],

    "Matches_Played": [237, 243, 250, 118, 176, 184, 123, 120, 226, 91],

    "Centuries": [8, 2, 0, 4, 4, 3, 0, 0, 0, 3],

    "Salary_Crore": [15, 16, 14, 11, 12.5, 11, 13, 12, 11.5, 8],

    "Department": [
        "Batsman",
        "Batsman",
        "Wicketkeeper",
        "Batsman",
        "Batsman",
        "Batsman",
        "All-rounder",
        "Bowler",
        "All-rounder",
        "Batsman"
    ],

    "Experience_Years": [16, 17, 19, 11, 14, 16, 9, 10, 14, 6]
}

In [98]:
df = pd.DataFrame(data)
df

,Player,Age,Matches_Played,Centuries,Salary_Crore,Department,Experience_Years
0,Virat Kohli,35,237,8,15.0,Batsman,16
1,Rohit Sharma,36,243,2,16.0,Batsman,17
2,MS Dhoni,42,250,0,14.0,Wicketkeeper,19
3,KL Rahul,32,118,4,11.0,Batsman,11
4,David Warner,37,176,4,12.5,Batsman,14
5,AB de Villiers,40,184,3,11.0,Batsman,16
6,Hardik Pandya,31,123,0,13.0,All-rounder,9
7,Jasprit Bumrah,30,120,0,12.0,Bowler,10
8,Ravindra Jadeja,35,226,0,11.5,All-rounder,14
9,Shubman Gill,25,91,3,8.0,Batsman,6

**Data Inspection**

In [99]:
df.head(3)

,Player,Age,Matches_Played,Centuries,Salary_Crore,Department,Experience_Years
0,Virat Kohli,35,237,8,15.0,Batsman,16
1,Rohit Sharma,36,243,2,16.0,Batsman,17
2,MS Dhoni,42,250,0,14.0,Wicketkeeper,19

In [100]:
df.tail(1)

,Player,Age,Matches_Played,Centuries,Salary_Crore,Department,Experience_Years
9,Shubman Gill,25,91,3,8.0,Batsman,6

In [101]:
df.shape

(10, 7)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Player            10 non-null     object
 1   Age               10 non-null     int64
 2   Matches_Played    10 non-null     int64
 3   Centuries         10 non-null     int64
 4   Salary_Crore      10 non-null     float64
 5   Department        10 non-null     object
 6   Experience_Years  10 non-null     int64
dtypes: float64(1), int64(4), object(2)
memory usage: 692.0+ bytes

In [103]:
df.describe()

            Age  Matches_Played  Centuries  Salary_Crore  Experience_Years
count  10.00000       10.000000  10.000000     10.000000         10.000000
mean   34.30000      176.800000   2.400000     12.400000         13.200000
std     4.98999       60.348617   2.590581      2.282786          4.077036
min    25.00000       91.000000   0.000000      8.000000          6.000000
25%    31.25000      120.750000   0.000000     11.125000         10.250000
50%    35.00000      180.000000   2.500000     12.250000         14.000000
75%    36.75000      234.250000   3.750000     13.750000         16.000000
max    42.00000      250.000000   8.000000     16.000000         19.000000

In [104]:
df.columns

Index(['Player', 'Age', 'Matches_Played', 'Centuries', 'Salary_Crore',
       'Department', 'Experience_Years'],
      dtype='object')

In [105]:
df.index

RangeIndex(start=0, stop=10, step=1)

**Column Selection**

In [106]:
df["Age"]

0    35
1    36
2    42
3    32
4    37
5    40
6    31
7    30
8    35
9    25
Name: Age, dtype: int64

In [107]:
df[["Player","Age"]]

            Player  Age
0      Virat Kohli   35
1     Rohit Sharma   36
2         MS Dhoni   42
3         KL Rahul   32
4     David Warner   37
5   AB de Villiers   40
6    Hardik Pandya   31
7   Jasprit Bumrah   30
8  Ravindra Jadeja   35
9     Shubman Gill   25

**Row Selection**

In [108]:
df.loc[0]

Player              Virat Kohli
Age                          35
Matches_Played              237
Centuries                     8
Salary_Crore               15.0
Department              Batsman
Experience_Years             16
Name: 0, dtype: object

**Filtering Data**

In [109]:
df[df["Age"] > 35]

,Player,Age,Matches_Played,Centuries,Salary_Crore,Department,Experience_Years
1,Rohit Sharma,36,243,2,16.0,Batsman,17
2,MS Dhoni,42,250,0,14.0,Wicketkeeper,19
4,David Warner,37,176,4,12.5,Batsman,14
5,AB de Villiers,40,184,3,11.0,Batsman,16

In [110]:
df[(df["Age"] > 35) & (df["Salary_Crore"] > 12)]

,Player,Age,Matches_Played,Centuries,Salary_Crore,Department,Experience_Years
1,Rohit Sharma,36,243,2,16.0,Batsman,17
2,MS Dhoni,42,250,0,14.0,Wicketkeeper,19
4,David Warner,37,176,4,12.5,Batsman,14

In [111]:
df.query("Age > 35")

,Player,Age,Matches_Played,Centuries,Salary_Crore,Department,Experience_Years
1,Rohit Sharma,36,243,2,16.0,Batsman,17
2,MS Dhoni,42,250,0,14.0,Wicketkeeper,19
4,David Warner,37,176,4,12.5,Batsman,14
5,AB de Villiers,40,184,3,11.0,Batsman,16

**Data Cleaning**

In [112]:
df.isnull().sum().sum()

np.int64(0)

In [113]:
df.notnull().sum().sum()

np.int64(70)

In [114]:
#df.dropna()
#df.fillna(0)

In [115]:
df.duplicated().sum()

np.int64(0)

In [116]:
#df.drop_duplicates()

**Modifying Data**

In [117]:
df["Bonus"] = df["Salary_Crore"] * 0.1
df

,Player,Age,Matches_Played,Centuries,Salary_Crore,Department,Experience_Years,Bonus
0,Virat Kohli,35,237,8,15.0,Batsman,16,1.50
1,Rohit Sharma,36,243,2,16.0,Batsman,17,1.60
2,MS Dhoni,42,250,0,14.0,Wicketkeeper,19,1.40
3,KL Rahul,32,118,4,11.0,Batsman,11,1.10
4,David Warner,37,176,4,12.5,Batsman,14,1.25
5,AB de Villiers,40,184,3,11.0,Batsman,16,1.10
6,Hardik Pandya,31,123,0,13.0,All-rounder,9,1.30
7,Jasprit Bumrah,30,120,0,12.0,Bowler,10,1.20
8,Ravindra Jadeja,35,226,0,11.5,All-rounder,14,1.15
9,Shubman Gill,25,91,3,8.0,Batsman,6,0.80

In [170]:
#df["Salary_in_Lakhs"] = df["Salary_Crore"] * 100

In [118]:
df = df.rename(columns={"Salary_Crore":"Salary"})

In [119]:
df = df.drop("Bonus",axis=1)

**Sorting**

In [120]:
df.sort_values("Age")

,Player,Age,Matches_Played,Centuries,Salary,Department,Experience_Years
9,Shubman Gill,25,91,3,8.0,Batsman,6
7,Jasprit Bumrah,30,120,0,12.0,Bowler,10
6,Hardik Pandya,31,123,0,13.0,All-rounder,9
3,KL Rahul,32,118,4,11.0,Batsman,11
8,Ravindra Jadeja,35,226,0,11.5,All-rounder,14
0,Virat Kohli,35,237,8,15.0,Batsman,16
1,Rohit Sharma,36,243,2,16.0,Batsman,17
4,David Warner,37,176,4,12.5,Batsman,14
5,AB de Villiers,40,184,3,11.0,Batsman,16
2,MS Dhoni,42,250,0,14.0,Wicketkeeper,19

In [121]:
df.sort_values("Salary",ascending=False)

,Player,Age,Matches_Played,Centuries,Salary,Department,Experience_Years
1,Rohit Sharma,36,243,2,16.0,Batsman,17
0,Virat Kohli,35,237,8,15.0,Batsman,16
2,MS Dhoni,42,250,0,14.0,Wicketkeeper,19
6,Hardik Pandya,31,123,0,13.0,All-rounder,9
4,David Warner,37,176,4,12.5,Batsman,14
7,Jasprit Bumrah,30,120,0,12.0,Bowler,10
8,Ravindra Jadeja,35,226,0,11.5,All-rounder,14
3,KL Rahul,32,118,4,11.0,Batsman,11
5,AB de Villiers,40,184,3,11.0,Batsman,16
9,Shubman Gill,25,91,3,8.0,Batsman,6

**Groupby Operators**

In [122]:
#df.groupby("Age").mean()

In [123]:
df.groupby("Department").sum()

,Player,Age,Matches_Played,Centuries,Salary,Experience_Years
Department,,,,,,
All-rounder,Hardik PandyaRavindra Jadeja,66,349,0,24.5,23
Batsman,Virat KohliRohit SharmaKL RahulDavid WarnerAB ...,205,1049,24,73.5,80
Bowler,Jasprit Bumrah,30,120,0,12.0,10
Wicketkeeper,MS Dhoni,42,250,0,14.0,19

In [124]:
df.groupby("Department").count()

              Player  Age  Matches_Played  Centuries  Salary  Experience_Years
Department
All-rounder        2    2               2          2       2                 2
Batsman            6    6               6          6       6                 6
Bowler             1    1               1          1       1                 1
Wicketkeeper       1    1               1          1       1                 1

In [125]:
df.groupby("Department")["Salary"].mean() #Avg Salary of a player in each department

Department
All-rounder     12.25
Batsman         12.25
Bowler          12.00
Wicketkeeper    14.00
Name: Salary, dtype: float64

In [126]:
#df.groupby("Department").agg("mean")
df.groupby("Department")["Salary"].agg(["mean", "min", "max"])

               mean   min   max
Department
All-rounder   12.25  11.5  13.0
Batsman       12.25   8.0  16.0
Bowler        12.00  12.0  12.0
Wicketkeeper  14.00  14.0  14.0

In [127]:
df["Centuries"].value_counts()

Centuries
0    4
3    2
4    2
8    1
2    1
Name: count, dtype: int64

**Merge / Join**

In [129]:
DF1 = pd.DataFrame({"ID": [1, 2, 3], "Name": ["A", "B", "C"]})
DF2 = pd.DataFrame({"ID": [1, 2, 4], "Score": [90, 80, 70]})

In [130]:
pd.merge(DF1,DF2,on="ID")
#DF1.merge(DF2, on="ID"

   ID Name  Score
0   1    A     90
1   2    B     80

In [131]:
pd.merge(DF1,DF2,on="ID",how="left")
#DF1.merge(DF2, on="ID", how="left")

   ID Name  Score
0   1    A   90.0
1   2    B   80.0
2   3    C    NaN

In [132]:
pd.concat([DF1,DF2])

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   90.0
1   2  NaN   80.0
2   4  NaN   70.0

In [140]:
DF3 = pd.DataFrame({"A": [1, 2, 3]}, index=["x", "y", "z"])
DF4 = pd.DataFrame({"B": [4, 5, 6]}, index=["x", "y", "z"])

1. Join on index (default)

In [141]:
DF3.join(DF4)

   A  B
x  1  4
y  2  5
z  3  6

2. Join with different indexes

In [142]:
DF5 = pd.DataFrame({"C": [7, 8]}, index=["x", "y"])
DF3.join(DF5, how="left")

   A    C
x  1  7.0
y  2  8.0
z  3  NaN

3. Join on a column instead of index

In [143]:
DF6 = pd.DataFrame({"key": ["x", "y", "z"], "D": [10, 11, 12]})
DF3.reset_index().join(DF6.set_index("key"), on="index")

  index  A   D
0     x  1  10
1     y  2  11
2     z  3  12

- If you see a TypeError, it’s usually because:

  - You passed something that isn’t a DataFrame/Series to join().

  - You didn’t align indexes properly.

  - You tried to join on a column without resetting/setting the index.

**Apply Functions**

In [156]:
import numpy as np

In [166]:
#apply → DataFrame, row/column-wise
#map → Series only, element-wise
#applymap → DataFrame, element-wise

In [145]:
df["Age"].apply(lambda x: x+1)

0    36
1    37
2    43
3    33
4    38
5    41
6    32
7    31
8    36
9    26
Name: Age, dtype: int64

In [149]:
# Column-wise mean
DF1.apply(np.mean, axis=0)

A    2.0
dtype: float64

In [158]:
# Row-wise sum
DF1.apply(np.sum, axis=1)

x    1
y    2
z    3
dtype: int64

In [164]:
s = pd.Series([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

s.map(lambda x: x**2)

0     121
1     144
2     169
3     196
4     225
5     256
6     289
7     324
8     361
9     400
10    441
dtype: int64

In [160]:
DF2.applymap(lambda x: x**2)

C:\Users\Prashanth Reddy\AppData\Local\Temp\ipykernel_19440\3487730544.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  DF2.applymap(lambda x: x**2)

    B
x  16
y  25
z  36

**Pivot Tables**

`pivot()` - Reshape data by turning unique values from one column into new columns.

In [178]:
DF = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT"],
    "Year": [2024, 2025, 2024, 2025],
    "Salary": [50000, 55000, 60000, 65000]
})

DF

  Department  Year  Salary
0         HR  2024   50000
1         HR  2025   55000
2         IT  2024   60000
3         IT  2025   65000

In [176]:
DF.pivot(index="Department", columns="Year", values="Salary")

Year         2024   2025
Department
HR          50000  55000
IT          60000  65000

`pivot_table()` - Similar to `pivot()`, but handles duplicates by applying an aggregation function.

In [179]:
DF.pivot_table(index="Department", columns="Year", values="Salary", aggfunc="mean")

Year           2024     2025
Department
HR          50000.0  55000.0
IT          60000.0  65000.0

In [186]:
DF1 = pd.DataFrame({
    "Region": ["North", "South", "North", "South", "East"],
    "Year": [2024, 2024, 2025, 2025, 2024],
    "Sales": [100, 200, 150, 250, 300]
})

DF1

  Region  Year  Sales
0  North  2024    100
1  South  2024    200
2  North  2025    150
3  South  2025    250
4   East  2024    300

In [188]:
pd.pivot_table(DF1, values="Sales", index="Region")

        Sales
Region
East    300.0
North   125.0
South   225.0

In [189]:
#Change aggregation function:
pd.pivot_table(DF1, values="Sales", index="Region", aggfunc="sum")

        Sales
Region
East      300
North     250
South     450

In [191]:
#Multiple aggregations:
pd.pivot_table(DF1, values="Sales", index="Region", aggfunc=["mean", "sum", "max"])

         mean   sum   max
        Sales Sales Sales
Region
East    300.0   300   300
North   125.0   250   150
South   225.0   450   250

In [192]:
#Add columns for grouping:
pd.pivot_table(DF1, values="Sales", index="Region", columns="Year", aggfunc="sum")

Year     2024   2025
Region
East    300.0    NaN
North   100.0  150.0
South   200.0  250.0